<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Modules\Column\Models\Column;
use Modules\Menu\Models\Menu;

class InsertDataToColumnsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $columnsData = [
            [
                'menu' => 'admin.customer.deletedCustomer',
                'columns' => [
                    [
                        'name' => "ID",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "first_name",
                        "description" => 'Name column',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Profile",
                        'code' => "profile_picture",
                        "description" => 'Profile picture ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Email",
                        'code' => "email",
                        "description" => 'Email ',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Contact Number",
                        'code' => "contact_number",
                        "description" => 'Contact Number',
                        "sort_order" => 5,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 6,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Deleted At",
                        'code' => "deleted_at",
                        "description" => 'Deleted At',
                        "sort_order" => 7,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],

                ]
            ],
            [
                'menu' => 'admin.customer.group.index',
                'columns' => [
                    [
                        'name' => "ID",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "name",
                        "description" => 'Name column',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 6,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.banner.index',
                'columns' => [
                    [
                        'name' => "ID",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Image",
                        'code' => "image",
                        "description" => 'Image',
                        "sort_order" => 2,
                        "is_sortable" => 2,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Title",
                        'code' => "title",
                        "description" => 'Title ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Banner Groups",
                        'code' => "banner_group_title",
                        "description" => 'Banner Groups ',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "URL",
                        'code' => "url",
                        "description" => 'URL',
                        "sort_order" => 5,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Code",
                        'code' => "code",
                        "description" => 'Code',
                        "sort_order" => 6,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 7,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.bannergroup.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "name",
                        "description" => 'Name',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Code",
                        'code' => "code",
                        "description" => 'Code ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 7,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.blog_category.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Title",
                        'code' => "title",
                        "description" => 'Title',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Status",
                        'code' => "status",
                        "description" => 'Status ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.blog_post.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Image",
                        'code' => "image",
                        "description" => 'Image',
                        "sort_order" => 2,
                        "is_sortable" => 2,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Title",
                        'code' => "title",
                        "description" => 'Title',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Auther",
                        'code' => "auther",
                        "description" => 'Auther ',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Slug",
                        'code' => "slug",
                        "description" => 'Slug ',
                        "sort_order" => 5,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Status",
                        'code' => "status",
                        "description" => 'Status ',
                        "sort_order" => 6,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Is Featured",
                        'code' => "is_featured",
                        "description" => 'Is Featured ',
                        "sort_order" => 7,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 8,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.blog_post_comment.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Subject",
                        'code' => "subject",
                        "description" => 'Subject',
                        "sort_order" => 2,
                        "is_sortable" => 2,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Post Title",
                        'code' => "title",
                        "description" => 'Post Title',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Customer Name",
                        'code' => "first_name",
                        "description" => 'Customer Name ',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Comment",
                        'code' => "comment",
                        "description" => 'Comment ',
                        "sort_order" => 5,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Status",
                        'code' => "status",
                        "description" => 'Status ',
                        "sort_order" => 6,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 8,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.contact.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "name",
                        "description" => 'Name',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Email Address",
                        'code' => "email",
                        "description" => 'Email Address',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Contact Number",
                        'code' => "contact_number",
                        "description" => 'Contact Number ',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 5,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.page.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Title",
                        'code' => "title",
                        "description" => 'Title',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Status",
                        'code' => "status",
                        "description" => 'Status ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.block.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Title",
                        'code' => "title",
                        "description" => 'Title',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Status",
                        'code' => "is_enabled",
                        "description" => 'Status ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.mail.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "name",
                        "description" => 'Name',
                        "sort_order" => 2,
                        "is_sortable" => 2,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Subject",
                        'code' => "subject",
                        "description" => 'Subject ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Slug",
                        'code' => "slug",
                        "description" => 'Slug ',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Cc",
                        'code' => "cc",
                        "description" => 'Cc ',
                        "sort_order" => 5,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Bcc",
                        'code' => "bcc",
                        "description" => 'Bcc ',
                        "sort_order" => 6,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Body",
                        'code' => "body",
                        "description" => 'Body ',
                        "sort_order" => 7,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Status",
                        'code' => "status",
                        "description" => 'Status ',
                        "sort_order" => 8,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 9,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.mail_log.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "From Email",
                        'code' => "from_email",
                        "description" => 'From Email',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "From Name",
                        'code' => "from_name",
                        "description" => 'From Name ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "To Email",
                        'code' => "to_email",
                        "description" => 'To Email ',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "To Name",
                        'code' => "to_name",
                        "description" => 'To Name ',
                        "sort_order" => 5,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Cc",
                        'code' => "cc",
                        "description" => 'Cc ',
                        "sort_order" => 6,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Bcc",
                        'code' => "bcc",
                        "description" => 'Bcc ',
                        "sort_order" => 6.1,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Subject",
                        'code' => "subject",
                        "description" => 'Subject ',
                        "sort_order" => 6.2,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Body",
                        'code' => "body",
                        "description" => 'Body ',
                        "sort_order" => 7,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Exception",
                        'code' => "exception",
                        "description" => 'Exception ',
                        "sort_order" => 7.1,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Status",
                        'code' => "status",
                        "description" => 'Status ',
                        "sort_order" => 8,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 9,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.attribute.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "name",
                        "description" => 'Name',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Code",
                        'code' => "code",
                        "description" => 'Code ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Input Type",
                        'code' => "input_type",
                        "description" => 'Input Type ',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Is Required",
                        'code' => "is_required",
                        "description" => 'Is Required ',
                        "sort_order" => 5,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Custom Value",
                        'code' => "custom_value",
                        "description" => 'Custom Value ',
                        "sort_order" => 6,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 7,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.cron.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Title",
                        'code' => "title",
                        "description" => 'Title',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Description",
                        'code' => "description",
                        "description" => 'Description ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Command",
                        'code' => "command",
                        "description" => 'Command ',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Cron Expression",
                        'code' => "cron_expression",
                        "description" => 'Cron Expression ',
                        "sort_order" => 5,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Status",
                        'code' => "status",
                        "description" => 'Status ',
                        "sort_order" => 6,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 7,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.schedule.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Title",
                        'code' => "title",
                        "description" => 'Title',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Command",
                        'code' => "command",
                        "description" => 'Command ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "message",
                        'code' => "message",
                        "description" => 'message ',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Executed Date",
                        'code' => "execute_date",
                        "description" => 'Executed Date ',
                        "sort_order" => 5,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Finished Date",
                        'code' => "finished_date",
                        "description" => 'Finished Date ',
                        "sort_order" => 5.1,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Status",
                        'code' => "status",
                        "description" => 'Status ',
                        "sort_order" => 6,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 7,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.role.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "name",
                        "description" => 'Name',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Slug",
                        'code' => "slug",
                        "description" => 'Slug ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.user.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "name",
                        "description" => 'Name',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Email",
                        'code' => "email",
                        "description" => 'Email ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Status",
                        'code' => "status",
                        "description" => 'Status ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.deleted_user.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "name",
                        "description" => 'Name',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Email",
                        'code' => "email",
                        "description" => 'Email ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Deleted At",
                        'code' => "deleated_at",
                        "description" => 'Deleted At ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.language.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Title",
                        'code' => "title",
                        "description" => 'Title',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Locale",
                        'code' => "locale",
                        "description" => 'Locale ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Status",
                        'code' => "status",
                        "description" => 'Status ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Is Default",
                        'code' => "is_default",
                        "description" => 'Is Default ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.customerloginlog.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "first_name",
                        "description" => 'Name',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Email",
                        'code' => "email",
                        "description" => 'Email ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Last Login Date",
                        'code' => "last_login_date",
                        "description" => 'Last Login Date ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ],
            [
                'menu' => 'admin.column.index',
                'columns' => [
                    [
                        'name' => "Id",
                        'code' => "id",
                        "description" => 'Id',
                        "sort_order" => 1,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Name",
                        'code' => "name",
                        "description" => 'Name',
                        "sort_order" => 2,
                        "is_sortable" => 1,
                        'is_default' => 1,
                    ],
                    [
                        'name' => "Code",
                        'code' => "code",
                        "description" => 'Code ',
                        "sort_order" => 3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Menu",
                        'code' => "menu",
                        "description" => 'Menu ',
                        "sort_order" => 3.1,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Description",
                        'code' => "description",
                        "description" => 'Description ',
                        "sort_order" => 3.2,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Sort Order",
                        'code' => "sort_order",
                        "description" => 'Sort Order ',
                        "sort_order" => 3.3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Is Sortable",
                        'code' => "is_sortable",
                        "description" => 'Is Sortable ',
                        "sort_order" => 3.3,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Is Default",
                        'code' => "is_default",
                        "description" => 'Is Default ',
                        "sort_order" => 3.4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                    [
                        'name' => "Created At",
                        'code' => "created_at",
                        "description" => 'Created At',
                        "sort_order" => 4,
                        "is_sortable" => 1,
                        'is_default' => 2,
                    ],
                ]
            ]
        ];
        $menu = New Menu();
        foreach ($columnsData as $key => $data) {
            $menuId = $menu->where('link', $data['menu'])->value('id');
            $data = array_map(function ($item) use ($menuId) {
                return ['menu_id' => $menuId] + $item;
            }, $data['columns']);
            Column::insert($data);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $module = new Columns();
        $module::truncate();
    }
}
